# Generated by Django 6.0.5 on 2026-05-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='nota',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
