# Generated by Django 6.0.5 on 2026-05-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0002_alter_jogo_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='review',
            field=models.TextField(max_length=5000),
        ),
    ]
